import type { BrawlerCharacter } from '@/types/brawler';

export const CHARACTERS: BrawlerCharacter[] = [
    {
        id: 1,
        name: 'Pikachu',
        maxHp: 80,
        speed: 7,
        jumpHeight: 22,
        attack: 12,
        defense: 5,
        elementType: 'electric',
        spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
        width: 80,
        height: 80,
        attackDetails: {
            damage: 12,
            knockback: 8,
            baseWidth: 50,
            baseHeight: 50,
        },
    },
    {
        id: 2,
        name: 'Charmander',
        maxHp: 90,
        speed: 6,
        jumpHeight: 20,
        attack: 14,
        defense: 6,
        elementType: 'fire',
        spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
        width: 80,
        height: 80,
        attackDetails: {
            damage: 14,
            knockback: 7,
            baseWidth: 60,
            baseHeight: 40,
        },
    },
    {
        id: 3,
        name: 'Bulbasaur',
        maxHp: 100,
        speed: 5,
        jumpHeight: 18,
        attack: 10,
        defense: 8,
        elementType: 'grass',
        spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
        width: 80,
        height: 80,
        attackDetails: {
            damage: 10,
            knockback: 6,
            baseWidth: 70,
            baseHeight: 60,
        },
    },
];
